### ISSUE TITLE
Versions compatible

### ISSUE THREAD

**Issue by sbernesto** [proversity-org/openedx-graded-discussion-xblock#3]
hi,

What versions of openedx is compatible? because i test on dogwood and i have this error

May 14 17:46:23 ginkgo [service_variant=cms][contentstore.views.preview][env:sandbox] WARNING [ginkgo  19770] [preview.py:318] - Unable to render student_view for <GradedDiscussionXBlockWithMixins @64E6 visible_to_staff_only=False, graded=False, annotation_token_secret=u'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', giturl=None, edxnotes=False, source_file=None, rubric=u'', course_edit_method=u'Studio', default_tab=None, in_entrance_exam=False, showanswer=u'attempted', display_name=<django.utils.functional.__proxy__ object at 0x7f7fe53058d0>, end_date=None, video_speed_optimizations=True, graceperiod=datetime.timedelta(0, 18000), format=None, due=None, start=datetime.datetime(2970, 1, 1, 5, 0, tzinfo=tzutc()), discussion_topic=u'All topics', video_bumper={}, start_date=None, max_attempts=None, parent=BlockUsageLocator(CourseLocator(u'edX', u'DemoX', u'Demo_Course', None, None), u'vertical', u'fefceaeea5984a3ca14d7b45e5d78afa'), tags=[], matlab_api_key=None, xqa_key=u'qaijS3UatK020Wc0sfCtFe0V6jpB4d64', grading_message=u'This discussion is staff graded. Your...', annotation_storage_url=u'http://your_annotation_storage.com', use_latex_compiler=False, days_early_for_beta=None, show_correctness=u'always', static_asset_path=u'', name=None, hide_from_toc=False, group_access={}, rerandomize=u'never', user_partitions=[], chrome=None, points=100, edxnotes_visibility=True, show_reset_button=False, self_paced=False>
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/preview.py", line 316, in get_preview_fragment
    fragment = module.render(preview_view, context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/core.py", line 202, in render
    return self.runtime.render(self, view, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1894, in render
    return self.__getattr__('render')(block, view_name, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1302, in render
    return super(MetricsMixin, self).render(block, view_name, context=context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/runtime.py", line 808, in render
    frag = view_fn(context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/graded_discussion/graded_discussion.py", line 293, in student_view
    frag = Fragment(LOADER.render_django_template("static/html/graded_discussion.html", self._get_context()))
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/graded_discussion/graded_discussion.py", line 366, in _get_context
    users=self.get_student_list(),
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/graded_discussion/graded_discussion.py", line 233, in get_student_list
    for user in users if not user.is_staff and user not in graded_students
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/graded_discussion/graded_discussion.py", line 390, in _get_contributions
    contributions = [contribution for contribution in self.contributions if contribution["author"] == username]
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/graded_discussion/graded_discussion.py", line 180, in contributions
    return self.api_discussion.get_contributions(self.topic_id)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/graded_discussion/graded_discussion.py", line 123, in api_discussion
    client_id = self.get_xblock_settings()["client_id"]
KeyError: 'client_id'

**Comment by ryangadams** [comment]
Hi @sbernesto, we've developed this against Ginkgo for now. It's not formally been open sourced (see no license!) but we are discussing internally our next steps in that regard. It's unlikely that we'd back-port it to older versions than Ginkgo, but if we do open source it you'll be more than welcome to fork and make it work!
